### ISSUE TITLE
Hide pom and unit test file when teacher upload Maven sample

### ISSUE THREAD

**Issue by fcumselab** [fcumselab/ProgEdu#17]
老師上傳Maven作業後
系統要保留pom檔跟unit test
學生作業在build時 需要換成系統保留的pom檔與unit test避免學生更改pom內容

**Comment by fcumselab** [comment]
改成:
只拉學生的src/下的目錄檔案
其他的檔案(pom檔test檔等等)都先存在tomcat上

**Comment by AngusHo53** [comment]
學生每次push 僅拉作業目錄src/底下的檔案進jenkins workspace內
maven與web版皆須做到以上目標
