### ISSUE TITLE
Optimize ProgEdu build workflow

### ISSUE THREAD

**Issue by fcumselab** [fcumselab/ProgEdu#20]
優化ProgEdu建置作業流程
原本:
建立GitLab專案->push第一筆->建立Jenkins job->手動執行第一筆initial建置
優化:
建立GitLab專案->建立Jenkins job->push第一筆->Jenkins輪詢偵測到push並建置第一筆initial

優點:
縮短建置作業的時間 預防超過輪詢時間並重複建置

**Comment by hoky841023** [comment]
不可行，jenkins scm輪詢依舊會重複觸發
